import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readdir,stat} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
await import('../scripts/build.mjs');
const root=resolve('dist');
async function files(dir){const result=[];for(const n of await readdir(dir)){const p=resolve(dir,n);if((await stat(p)).isDirectory())result.push(...await files(p));else result.push(p);}return result;}
const built=await files(root);const htmlFiles=built.filter(p=>extname(p)==='.html');
test('course preserves 12 lesson pages, 7 units, setup and 20 teaching hours',async()=>{const data=JSON.parse(await readFile('content/course.json'));assert.equal(data.lessons.length,12);assert.equal(data.units.length,7);assert.equal(data.lessons.reduce((s,p)=>s+p.hours,0),20);for(const d of [1,2,3])assert.equal(data.lessons.filter(p=>p.day===d).reduce((s,p)=>s+p.hours,0),d===3?4:8);assert.equal(htmlFiles.length,22);});
test('all local page, asset and anchor targets exist',async()=>{for(const f of htmlFiles){const html=await readFile(f,'utf8');for(const m of html.matchAll(/(?:href|src)="([^"]+)"/g)){const link=m[1];if(!link.startsWith('/kpc-lec/')&&!link.startsWith('#'))continue;const [path,anchor]=link.split('#');let target=path?resolve(root,path.replace('/kpc-lec/','')):f;if(!extname(target))target=resolve(target,'index.html');assert.ok(built.includes(target),`${f}: ${link}`);if(anchor){const targetHtml=await readFile(target,'utf8');assert.ok(targetHtml.includes(`id="${anchor}"`),`${link}: missing anchor`);}}}});
test('TTS read markers, exclusions, copy controls and next/previous navigation are present',async()=>{const p=await readFile('dist/lessons/d1-p01/index.html','utf8');assert.match(p,/data-tts-content/);assert.match(p,/class="tts-readable"/);assert.match(p,/code-wrap" data-tts-exclude/);assert.match(p,/aria-label="이전 다음 수업"/);assert.match(p,/Cmd\+C \/ Cmd\+V/);assert.match(p,/reader\.mjs/);});
test('early lessons do not require ZIP; data lesson has download and beginner blank-cell explanation',async()=>{for(const s of ['d1-p01','d1-p02-03','d1-p04-05','d1-p06']){const p=await readFile(`content/periods/${s}.md`,'utf8');assert.ok(!p.includes('releases/latest/download'));}const data=await readFile('content/periods/d1-p07-08.md','utf8');assert.match(data,/releases\/latest\/download/);const pandas=await readFile('content/periods/d1-p04-05.md','utf8');assert.ok(pandas.indexOf('빈칸')<pandas.indexOf('결측치'));});
test('published assets have no raw PDFs, notebooks, names or local paths',async()=>{for(const f of built){assert.ok(!/\.(pdf|xlsx|csv|ipynb)$/i.test(f),f);if(extname(f)==='.html'){const s=await readFile(f,'utf8');assert.ok(!s.includes('C:\\works\\')&&!s.includes('수강생명단')&&!s.includes('surl:'),f);}}});
test('unit tables keep all 27 official learning items',async()=>{const {units}=JSON.parse(await readFile('content/course.json'));let count=0;for(const u of units){const s=await readFile(`content/${u.slug}.md`,'utf8');const menu=s.split('## 단원 목차')[1].split('\n## ')[0];count+=(menu.match(/^\d+\. /gm)||[]).length;}assert.equal(count,27);});
